- platform: miflora
  name: 'Plant 1'
  mac: 'C4:7C:8D:66:4F:8B'
  median: 3
  timeout: 30

- platform: miflora
  name: 'Plant 2'
  mac: 'C4:7C:8D:66:47:D5'
  median: 3
  timeout: 30

- platform: miflora
  mac: 'C4:7C:8D:66:38:35'
  name: 'Plant 3'
  median: 3
  timeout: 30

- platform: miflora
  name: 'Plant 4'
  mac: C4:7C:8D:66:37:13
  median: 3
  timeout: 30
