- platform: netatmo
  station: Romolslia
  modules:
    Stue:
      - temperature
      - humidity
      - co2
      - noise
      - min_temp
      - max_temp
    Bakside:
      - temperature
      - co2
      - pressure
      - humidity
      - rain # Estimated rainfall for today in mm.
      - sum_rain_1 # Rainfall in the last hour in mm.
      - sum_rain_24 # Rainfall in mm from 00:00am - 23:59pm.
      - windangle
      - windstrength
      - gustangle
      - guststrength
      - min_temp
      - max_temp
      - rf_status
      - wifi_status
      - battery_vp
