- platform: mqtt
  state_topic: 'hass/living_room/receiver/sensor'
  name: 'Receiver temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'hass/living_room/receiver/sensor'
  name: 'Receiver humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
