- platform: template
  sensors:
    solar_angle:
      value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.azimuth) }}'
      friendly_name: 'Solvinkel'
      unit_of_measurement: '°'

    sun_elevation:
      value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
      friendly_name: 'Høyde'
      unit_of_measurement: '°'
      icon_template: mdi:weather-sunset


    ### Smoke sensors
  
    # Gang
    smoke_gang:
      value_template: '{% if is_state("sensor.smoke_entrance_smoke_2", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk i gangen'
      icon_template: '{% if is_state("sensor.smoke_entrance_smoke_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      
    heat_gang:
      value_template: '{% if is_state("sensor.smoke_entrance_heat_2", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme i gangen'
      icon_template: '{% if is_state("sensor.smoke_entrance_heat_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'

    # Kontor
    smoke_kontor:
      value_template: '{% if is_state("sensor.smoke_office_smoke_2", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk på kontoret'
      icon_template: '{% if is_state("sensor.smoke_office_smoke_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      
    heat_kontor:
      value_template: '{% if is_state("sensor.smoke_office_heat_2", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme på kontoret'
      icon_template: '{% if is_state("sensor.smoke_office_heat_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'

    # Stue
    smoke_stue:
      value_template: '{% if is_state("sensor.smoke_living_room_smoke_2", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk i stua'
      icon_template: '{% if is_state("sensor.smoke_living_room_smoke_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      
    heat_stue:
      value_template: '{% if is_state("sensor.smoke_living_room_heat_2", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme i stua'
      icon_template: '{% if is_state("sensor.smoke_living_room_heat_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'

    # Soverom
    smoke_soverom:
      value_template: '{% if is_state("sensor.smoke_soverom_smoke_2", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk på soverommet'
      icon_template: '{% if is_state("sensor.smoke_soverom_smoke_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      
    heat_soverom:
      value_template: '{% if is_state("sensor.smoke_soverom_heat_2", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme på soverommet'
      icon_template: '{% if is_state("sensor.smoke_soverom_heat_2", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'

    template_water_leak_kitchen:
      value_template: '{% if is_state("sensor.kitchen_leak_sensor_flood", "0") %}OK{% else %}Vannlekkasje!{% endif %}'
      icon_template: '{% if is_state("sensor.kitchen_leak_sensor_flood", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
      friendly_name: Vannlekkasje


    # Battery sensors
    battery_danalock:
      friendly_name: Danalock
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.danalock', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_door_front:
      friendly_name: Dør foran
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.door_front', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_door_back:
      friendly_name: Dør bak
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.door_back', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_smoke_living_room:
      friendly_name: Røykvarsler stue
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.smoke_living_room', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_smoke_bedroom:
      friendly_name: Røykvarsler soverom
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.smoke_soverom', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_smoke_entrance:
      friendly_name: Røykvarsler gang
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.smoke_entrance', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_smoke_office:
      friendly_name: Røykvarsler kontor
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.smoke_office', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_multi_kitchen:
      friendly_name: Multisensor kjøkken
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.multi_kitchen_bottom', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_multi_entrance:
      friendly_name: Multisensor gang
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.multi_gang', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_refrigerator:
      friendly_name: Kjøleskapet på kjøkkenet
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.refrigerator_kitchen', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_freezer_kitchen:
      friendly_name: Fryser på kjøkkenet
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.freezer_kitchen', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}

    battery_freezer_bod:
      friendly_name: Fryser i boden
      unit_of_measurement: '%'
      icon_template: mdi:battery-10
      value_template: >-
          {% set battery = state_attr('zwave.freezer_bod', 'battery_level') %}
          {% if battery is number %}
              {{ battery | round }}
          {% else %}
              N/A
          {%- endif %}


    # Receiver
    template_receiver_rear:
      friendly_name: 'Vifte bak'
      unit_of_measurement: '%'
      value_template: >-
        {% if is_state('input_number.receiver_fan_speed_rear', '0.0') %}
          0
        {% else %}
          {{ states.input_number.receiver_fan_speed_rear.state | int }}
        {% endif %}
      icon_template: >-
        {% if is_state('input_number.receiver_fan_speed_rear', '0.0') %}
          mdi:fan-off
        {% else %}
          mdi:fan
        {% endif %}

    template_receiver_internal:
      friendly_name: 'Vifte intern'
      unit_of_measurement: '%'
      value_template: >-
        {% if is_state('input_number.receiver_fan_speed_internal', '0.0') %}
          0
        {% else %}
          {{ states.input_number.receiver_fan_speed_internal.state | int }}
        {% endif %}
      icon_template: >-
        {% if is_state('input_number.receiver_fan_speed_internal', '0.0') %}
          mdi:fan-off
        {% else %}
          mdi:fan
        {% endif %}

    bod_temperature:
      friendly_name: 'Bod temperatur'
      unit_of_measurement: '°C'
      value_template: '{{ states.sensor.bod_temperature.attributes.temperature }}'
      icon_template: mdi:thermometer


    stale_home_bluetooth:
      friendly_name: 'Ståle iPhone home'
      value_template: >-
        {% set home = 10 %}
        {% if home is number and home > 0 %}
            home
        {% else %}
            not_home
        {%- endif %}


    elecricity_price_percent:
      friendly_name: 'Strømpris prosent'
      unit_of_measurement: '%'
      value_template: >-
        {% set min = float(states.sensor.electricity_price_romolslia_78.attributes.min_price) %}
        {% set max = float(states.sensor.electricity_price_romolslia_78.attributes.max_price) %}
        {% set current = float(states.sensor.electricity_price_romolslia_78.state) %}
        {% if min is not number or max is not number or current is not number %}
          None
        {% else %}
          {{ ((0.672 - min) / (max - min) * 100) | round(1) }}
        {% endif %}


    elecricity_price_percent_above:
      friendly_name: 'Strømpris prosent'
      unit_of_measurement: '%'
      value_template: >-
        {% set min = float(states.sensor.electricity_price_romolslia_78.attributes.min_price) %}
        {% set max = float(states.sensor.electricity_price_romolslia_78.attributes.max_price) %}
        {% if min is not number or max is not number %}
          None
        {% else %}
          {{ ((max / min) * 100) | round(1) }}
        {% endif %}


    electricity_temperature:
      friendly_name: 'Temperatur korrigering'
      unit_of_measurement: '°C'
      value_template: >-
        {% set min = float(states.sensor.electricity_price_romolslia_78.attributes.min_price) %}
        {% set max = float(states.sensor.electricity_price_romolslia_78.attributes.max_price) %}
        {% set current = float(states.sensor.electricity_price_romolslia_78.state) %}
        {% set value = ((((current - min) / (max - min)) - 0.5) * -1) %}
        {% set percent = float(states.sensor.elecricity_price_percent_above.state) %}
        {% if min is not number or max is not number or current is not number or value is not number or percent is not number %}
          None
        {% else %}
          {{ (value * (percent / 100)) | round(1) }}
        {% endif %}


    living_room_fireplace_kitchen:
      value_template: '{% if is_state("living_room_fireplace", "on") %}0{% else %}1.5{% endif %}'

    living_room_fireplace_living_room:
      value_template: '{% if is_state("living_room_fireplace", "on") %}0{% else %}2{% endif %}'
