- platform: workday
  country: 'NO'
  name: 'today'

- platform: workday
  country: 'NO'
  days_offset: 1
  name: 'tomorrow'

- platform: workday
  country: 'NO'
  days_offset: -1
  name: 'yesterday'
