- platform: workday
  country: 'NO'
  name: 'workday_today'

- platform: workday
  country: 'NO'
  days_offset: 1
  name: 'workday_tomorrow'

- platform: workday
  country: 'NO'
  days_offset: -1
  name: 'workday_yesterday'

- platform: command_line
  name: Tina jobb i dag sjekk
  scan_interval: 3600
  payload_on: 'true'
  payload_off: 'false'
  command: python3 /home/homeassistant/scripts/python/gcal/gcal_today.py

- platform: command_line
  name: Tina jobb i morgen sjekk
  scan_interval: 3600
  payload_on: 'true'
  payload_off: 'false'
  command: python3 /home/homeassistant/scripts/python/gcal/gcal_tomorrow.py
