- platform: generic_thermostat
  name: Stue termostat
  heater: switch.panelovn_stue_switch_11_0
  target_sensor: sensor.temp_stue_temperature
  min_temp: 10
  max_temp: 24
  target_temp: 18
  tolerance: 0.1
  min_cycle_duration:
    minutes: 1

- platform: generic_thermostat
  name: Kontor termostat
  heater: switch.panelovn_kontor_switch_44_0
  target_sensor: sensor.temp_kontor_temperature
  min_temp: 10
  max_temp: 23
  target_temp: 18
  tolerance: 0.1
  min_cycle_duration:
    minutes: 1

- platform: generic_thermostat
  name: Soverom termostat
  heater: switch.panelovn_soverom_switch_13_0
  target_sensor: sensor.temp_soverom_temperature
  min_temp: 10
  max_temp: 21
  target_temp: 19
  tolerance: 0.1
  min_cycle_duration:
    minutes: 1
