homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 82
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

frontend:

#panel_iframe: !include panel_iframe.yaml

http:
  api_password: !secret http_password
  base_url: !secret my_domain
  server_port: 8123
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: True

config:

updater:

discovery:
  ignore:
    - apple_tv
    - plex_mediaserver

history:

recorder: !include recorder.yaml
logbook: !include logbook.yaml

sun:

mqtt:

ios:

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Z5XR3V-if00-port0

climate: !include climate.yaml
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensors/
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups/
scene: !include_dir_merge_list scenes/
camera: !include camera.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
input_slider: !include input_slider.yaml
binary_sensor: !include binary_sensor.yaml
shell_command: !include_dir_merge_named shell_command/
media_player: !include media_player.yaml

zwave:
  usb_path: /dev/ttyAMA0

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code

notify: !include notify.yaml
