homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 82
  unit_system: metric
  time_zone: Europe/Oslo
  customize_glob:
    "*":
      custom_ui_state_card: state-card-custom-ui
  customize: !include_dir_merge_named ui/customize/
  whitelist_external_dirs:
    - /home/homeassistant/heracam/fullsize
    - /home/homeassistant/heracam/thumbnail
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

auth:

frontend: !include ui/frontend.yaml

http: !include http.yaml

config:

updater:
  include_used_components: true

discovery:
  ignore:
    - plex_mediaserver
    - apple_tv

python_script:

# History
history:
recorder: !include recorder.yaml
logbook: !include logbook.yaml
logger:
  default: warning
  logs:
    homeassistant.components.media_player: error
    homeassistant.components.sensor.template: error

automation: !include_dir_merge_list automation/
group: !include_dir_merge_named groups/

### Devices
alarm_control_panel: !include devices/alarm.yaml
camera: !include devices/camera.yaml
climate: !include devices/climate.yaml
device_tracker: !include devices/device_tracker.yaml
ios: !include devices/ios.yaml
mqtt: !include devices/mqtt.yaml
hue: !include devices/hue.yaml
sensor: !include_dir_merge_list input/sensors/
apple_tv: !include devices/apple_tv.yaml

### Scenes
scene: !include_dir_merge_list scenes/

### Input
binary_sensor: !include_dir_merge_list input/binary_sensors/
input_boolean: !include_dir_merge_named input/input_booleans/
input_datetime: !include_dir_merge_named input/input_datetime/
input_number: !include_dir_merge_named input/input_numbers/
media_player: !include devices/media_player.yaml
shell_command: !include_dir_merge_named devices/shell_commands/
switch: !include_dir_merge_list devices/switch/
sun:

history_graph:
  temperature_outside:
    name: 'Temperatur siste 48 timer'
    hours_to_show: 48
    refresh: 120
    entities:
      - sensor.temp_ute_temperature

### Connected devices
rfxtrx: !include devices/rfxtrx.yaml
zwave: !include devices/zwave.yaml
netatmo: !include devices/netatmo.yaml

### Push
notify: !include notify.yaml

### Scripts
script: !include scripts.yaml
