homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 82
  unit_system: metric
  time_zone: Europe/Oslo
  customize_glob:
    "*":
      homebridge_hidden: true
      # custom_ui_state_card: state-card-custom-ui
  customize: !include_dir_merge_named ui/customize/
  whitelist_external_dirs:
    - /home/homeassistant/heracam/fullsize
    - /home/homeassistant/heracam/thumbnail

frontend: !include ui/frontend.yaml

http: !include http.yaml

config:

updater:
  include_used_components: true

discovery:
  ignore:
    - plex_mediaserver
    - apple_tv

# History
history:
recorder: !include recorder.yaml
logbook: !include logbook.yaml
logger:
  default: error

automation: !include_dir_merge_list automation/
group: !include_dir_merge_named groups/

### Devices
alarm_control_panel: !include devices/alarm.yaml
camera: !include devices/camera.yaml
climate: !include devices/climate.yaml
device_tracker: !include devices/device_tracker.yaml
ios: !include devices/ios.yaml
mqtt: !include devices/mqtt.yaml
light: !include devices/light.yaml
sensor: !include_dir_merge_list input/sensors/
apple_tv: !include devices/apple_tv.yaml

### Scenes
scene: !include_dir_merge_list scenes/

### Input
binary_sensor: !include_dir_merge_list input/binary_sensors/
input_boolean: !include_dir_merge_named input/input_booleans/
input_datetime: !include_dir_merge_named input/input_datetime/
input_number: !include_dir_merge_named input/input_numbers/
media_player: !include devices/media_player.yaml
shell_command: !include_dir_merge_named devices/shell_commands/
switch: !include_dir_merge_list devices/switch/
sun:
netatmo: !include devices/netatmo.yaml

### Connected devices
# 433mhz
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Z5XR3V-if00-port0

# Z-wave
zwave:
  usb_path: /dev/ttyAMA0
  polling_interval: 1800000
  network_key: !secret zwave_key

### Push
notify: !include notify.yaml

### Scripts
script: !include scripts.yaml
