- platform: nmap_tracker
  # Seconds to wait till marking someone as not home after not being seen
  consider_home: 900
  # Seconds between each scan for new devices
  interval_seconds: 60
  # The number of minutes nmap will not scan this device, assuming it is home
  home_interval: 3
  hosts:
    - 10.0.0.65
    - 10.0.0.66

- platform: locative

- platform: geofency
