#device_tracker:
#  - platform: icloud
#    username: stale.hauknes@me.com
#    password: !include device_tracker_pwd
#    account_name: Ståle iCloud

- platform: nmap_tracker
  consider_home: 300
  interval_seconds: 180
  home_interval: 15
  hosts:
    - 10.0.0.66
