- platform: command_line
  name: Tina jobb i dag sjekk
  scan_interval: 600
  payload_on: 'true'
  payload_off: 'false'
  command: python3 /home/homeassistant/scripts/python/gcal/gcal_today.py

- platform: command_line
  name: Tina jobb i morgen sjekk
  scan_interval: 600
  payload_on: 'true'
  payload_off: 'false'
  command: python3 /home/homeassistant/scripts/python/gcal/gcal_tomorrow.py
