- platform: mqtt
  name: 'Doorbell relay'
  state_topic: 'hass/entrance/doorbell/switch'
  command_topic: 'hass/entrance/doorbell/switch/set'
  payload_on: 'on'
  payload_off: 'off'
  qos: 1
  retain: true
