- platform: mqtt
  name: 'Doorbell relay'
  state_topic: 'hass/entrance/doorbell/switch'
  command_topic: 'hass/entrance/doorbell/switch/set'
  payload_on: '1'
  payload_off: '0'
  qos: 1
  retain: true
