- platform: mqtt
  name: 'HeraCam relay'
  state_topic: 'hass/entrance/heracam/switch'
  command_topic: 'hass/entrance/heracam/switch/set'
  payload_on: '1'
  payload_off: '0'
  qos: 1
  retain: true
