- platform: mqtt
  name: 'HeraCam relay'
  state_topic: 'hass/entrance/heracam/switch'
  command_topic: 'hass/entrance/heracam/switch/set'
  payload_on: 'on'
  payload_off: 'off'
  qos: 1
  retain: true
