- platform: template
  sensors:
    solar_angle:
      value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.azimuth) }}'
      friendly_name: 'Solvinkel'
      unit_of_measurement: '°'

    # Motion
    motion_gang:
      value_template: '{% if is_state("sensor.multi_gang_burglar_17_10", "0") %}Ingen bevegelse{% else %}Bevegelse!{% endif %}'
      friendly_name: 'Motion gang'
      icon_template: '{% if is_state("sensor.multi_gang_burglar_17_10", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'

    motion_kitchen:
      value_template: '{% if is_state("sensor.multi_kitchen_burglar_18_10", "0") %}Ingen bevegelse{% else %}Bevegelse!{% endif %}'
      friendly_name: 'Motion kjøkken'
      icon_template: '{% if is_state("sensor.multi_kitchen_burglar_18_10", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
      
    motion_kontor:
      value_template: '{% if is_state("sensor.multi_kontor_burglar_9_10", "0") %}Ingen bevegelse{% else %}Bevegelse!{% endif %}'
      friendly_name: 'Motion kontor'
      icon_template: '{% if is_state("sensor.multi_kontor_burglar_9_10", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
