- platform: template
  sensors:
    solar_angle:
      value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.azimuth) }}'
      friendly_name: 'Solvinkel'
      unit_of_measurement: '°'

    # Motion
    alarm_active:
      value_template: >-
          {% set stale = is_state("input_boolean.stale_home", "off") %}
          {% set tina = is_state("input_boolean.tina_home", "off") %}
          {% set guests = is_state("input_boolean.guests", "off") %}
          {% set android1 = is_state("device_tracker.android89bc5926ba332e4flan", "not_home") %}
          {% set android2 = is_state("device_tracker.samsunggalaxys7lan", "not_home") %}
          {%- if stale and tina and guests and android %}
            Active
          {% else %}
            Inactive
          {% endif %}
      friendly_name: Alarm state
      entity_id:
        - input_boolean.stale_home
        - input_boolean.tina_home
        - input_boolean.guests
        - device_tracker.android89bc5926ba332e4flan
        - device_tracker.samsunggalaxys7lan

    motion_gang:
      value_template: >-
          {% if is_state("sensor.multi_gang_burglar_17_10", "0") %}
            {{ as_timestamp(states.sensor.multi_gang_burglar_17_10.last_changed) | timestamp_custom("%d.%m.%Y - %H:%M", True) }}
          {% else %}Bevegelse!{% endif %}
      friendly_name: 'Motion gang'
      icon_template: '{% if is_state("sensor.multi_gang_burglar_17_10", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
      entity_id:
        - sensor.multi_gang_burglar_17_10

    motion_kitchen:
      value_template: >-
          {% if is_state("sensor.multi_kitchen_burglar_18_10", "0") %}
            {{ as_timestamp(states.sensor.multi_kitchen_burglar_18_10.last_changed) | timestamp_custom("%d.%m.%Y - %H:%M", True) }}
          {% else %}Bevegelse!{% endif %}
      friendly_name: 'Motion kjøkken'
      icon_template: '{% if is_state("sensor.multi_kitchen_burglar_18_10", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
      entity_id:
        - sensor.multi_kitchen_burglar_18_10
      
    motion_kontor:
      value_template: >-
          {% if is_state("sensor.multi_kontor_burglar_9_10", "0") %}
            {{ as_timestamp(states.sensor.multi_kontor_burglar_9_10.last_changed) | timestamp_custom("%d.%m.%Y - %H:%M", True) }}
          {% else %}Bevegelse!{% endif %}
      friendly_name: 'Motion kontor'
      icon_template: '{% if is_state("sensor.multi_kontor_burglar_9_10", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
      entity_id:
        - sensor.multi_kontor_burglar_9_10


    ### Smoke sensors
  
    # Gang
    smoke_gang:
      value_template: '{% if is_state("sensor.smoke_gang_smoke_47_1", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk i gangen'
      icon_template: '{% if is_state("sensor.smoke_gang_smoke_47_1", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_gang_smoke_47_1
      
    heat_gang:
      value_template: '{% if is_state("sensor.smoke_gang_heat_47_4", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme i gangen'
      icon_template: '{% if is_state("sensor.smoke_gang_heat_47_4", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_gang_heat_47_4

    # Kontor
    smoke_kontor:
      value_template: '{% if is_state("sensor.smoke_kontor_smoke_48_1", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk på kontoret'
      icon_template: '{% if is_state("sensor.smoke_kontor_smoke_48_1", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_kontor_smoke_48_1
      
    heat_kontor:
      value_template: '{% if is_state("sensor.smoke_kontor_heat_48_4", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme på kontoret'
      icon_template: '{% if is_state("sensor.smoke_kontor_heat_48_4", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_kontor_heat_48_4

    # Stue
    smoke_stue:
      value_template: '{% if is_state("sensor.smoke_stue_smoke_49_1", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk i stua'
      icon_template: '{% if is_state("sensor.smoke_stue_smoke_49_1", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_stue_smoke_49_1
      
    heat_stue:
      value_template: '{% if is_state("sensor.smoke_stue_heat_49_4", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme i stua'
      icon_template: '{% if is_state("sensor.smoke_stue_heat_49_4", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_stue_heat_49_4

    # Soverom
    smoke_soverom:
      value_template: '{% if is_state("sensor.smoke_soverom_smoke_50_1", "0") %}OK{% else %}Brann!!{% endif %}'
      friendly_name: 'Røyk på soverommet'
      icon_template: '{% if is_state("sensor.smoke_soverom_smoke_50_1", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_soverom_smoke_50_1
      
    heat_soverom:
      value_template: '{% if is_state("sensor.smoke_soverom_heat_50_4", "0") %}OK{% else %}Veldig varmt!!{% endif %}'
      friendly_name: 'Varme på soverommet'
      icon_template: '{% if is_state("sensor.smoke_soverom_heat_50_4", "0") %}mdi:bell-outline{% else %}mdi:bell-ring{% endif %}'
      entity_id:
        - sensor.smoke_soverom_heat_50_4
    
    # Template temperature / humidity sensors with fallback
    template_temperature_bedroom:
      value_template: >-
          {% set mqtt_updated = as_timestamp(states.sensor.mqtt_bedroom_temperature.last_updated) %}
          {% set rfx433_updated = as_timestamp(states.sensor.temp_soverom_temperature.last_updated) %}
          {% set now = as_timestamp(utcnow()) %}
          {% if is_state("sensor.sensor.mqtt_bedroom_humidity", "0") or is_state("sensor.mqtt_bedroom_humidity", "unknown") %}
            {{ states.sensor.temp_soverom_temperature.state | float }}
          {% elif (now - mqtt_updated) < 1800 or mqtt_updated > rfx433_updated %}
            {{ states.sensor.mqtt_bedroom_temperature.state | float }}
          {% else %}
            {{ states.sensor.temp_soverom_temperature.state | float }}
          {% endif %}
      friendly_name: Temperatur soverom
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
      entity_id:
        - sensor.temp_soverom_temperature
        - sensor.mqtt_bedroom_temperature

    template_humidity_bedroom:
      value_template: >-
          {% set mqtt_updated = as_timestamp(states.sensor.mqtt_bedroom_humidity.last_updated) %}
          {% set rfx433_updated = as_timestamp(states.sensor.temp_soverom_humidity.last_updated) %}
          {% set now = as_timestamp(utcnow()) %}
          {% if is_state("sensor.sensor.mqtt_bedroom_humidity", "0") or is_state("sensor.mqtt_bedroom_humidity", "unknown") %}
            {{ states.sensor.temp_soverom_humidity.state | float }}
          {% elif (now - mqtt_updated) < 1800 or mqtt_updated > rfx433_updated %}
            {{ states.sensor.mqtt_bedroom_humidity.state | float }}
          {% else %}
            {{ states.sensor.temp_soverom_humidity.state | float }}
          {% endif %}
      friendly_name: Luftfuktighet
      icon_template: mdi:percent
      unit_of_measurement: '%'
      entity_id:
        - sensor.temp_soverom_humidity
        - sensor.mqtt_bedroom_humidity

    template_water_leak_kitchen:
      value_template: '{% if is_state("sensor.kitchen_leak_sensor_flood_32_5", "0") %}OK{% else %}Vannlekkasje!{% endif %}'
      icon_template: '{% if is_state("sensor.kitchen_leak_sensor_flood_32_5", "0") %}mdi:alert-circle-outline{% else %}mdi:alert-circle{% endif %}'
      friendly_name: Vannlekkasje
      entity_id:
        - sensor.kitchen_leak_sensor_flood_32_5
