- platform: generic_thermostat
  name: Stue termostat
  heater: switch.panelovn_stue_switch
  target_sensor: sensor.temp_stue_temperature
  min_temp: 10
  max_temp: 25
  target_temp: 22
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes:
      30

- platform: generic_thermostat
  name: Kontor termostat
  heater: switch.panelovn_kontor_switch
  target_sensor: sensor.temp_kontor_temperature
  min_temp: 10
  max_temp: 23
  target_temp: 18
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes:
      30

- platform: generic_thermostat
  name: Soverom thermostat
  heater: switch.panelovn_soverom_switch
  target_sensor: sensor.template_temperature_bedroom
  min_temp: 10
  max_temp: 22
  target_temp: 19
  cold_tolerance: 0.1
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 30
  keep_alive:
    minutes:
      30

- platform: generic_thermostat
  name: Gang termostat
  heater: switch.ovn_gang_switch
  target_sensor: sensor.multi_gang_temperature
  min_temp: 10
  max_temp: 22
  target_temp: 20
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes:
      30
