- alias: Alarm away door kjøkken
  trigger:
    - platform: state
      entity_id: binary_sensor.door_back_sensor_53_0
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.ios_lolphone_7
      data:
        message: 'Door alarm!'
        title: 'Døra på baksiden er åpnet!'


- alias: Alarm away kontor
  trigger:
    - platform: state
      entity_id: binary_sensor.door_front_sensor_52_0
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.ios_lolphone_7
      data:
        message: 'Door alarm!'
        title: 'Døra på framsiden er åpnet!'
