- alias: Alarm away gang
  trigger:
    - platform: state
      entity_id: sensor.motion_gang
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse i gangen!'
        attachment:
          url: https://h0me.no/api/camera_proxy_stream/camera.heracam?token=043bef10ad01d29b7b25df5ca8f980355bd0ee922dbbe1b6c93a9b204c57a5ef
          content-type: jpeg
          hide-thumbnail: false


- alias: Alarm away kjøkken
  trigger:
    - platform: state
      entity_id: sensor.motion_kitchen
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kjøkkenet!'


- alias: Alarm away kontor
  trigger:
    - platform: state
      entity_id: sensor.motion_kontor
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kontoret!'
