- alias: Arm alarm (Ståle)
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'off'
    - platform: state
      entity_id: sensor.stale_home_bluetooth
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: lock.danalock_locked
      state: 'locked'
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: pending
  action:
    - service: notify.ios_lolphone_x
      data:
        message: "Drar bort: alarm ikke aktivert"
        data:
          push:
            badge: 0
            category: "arm_alarm_stale"
    - service: input_boolean.turn_off
      entity_id: input_boolean.stale_alarm_notifications

- alias: Ask if alarm should be armed (Ståle)
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'off'
    - platform: state
      entity_id: sensor.stale_home_bluetooth
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: lock.danalock_locked
      state: 'unlocked'
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: pending
  action:
    - service: notify.ios_lolphone_x
      data:
        message: "Drar bort: dør ulåst og alarm ikke aktivert"
        data:
          push:
            badge: 0
            category: "arm_alarm_and_lock_door_stale"
    - service: input_boolean.turn_off
      entity_id: input_boolean.stale_alarm_notifications

- alias: Ask if door should be locked (Ståle)
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'off'
    - platform: state
      entity_id: sensor.stale_home_bluetooth
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: lock.danalock_locked
      state: 'unlocked'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'armed_away'
  action:
    - service: notify.ios_lolphone_x
      data:
        message: "Drar bort: dør ulåst"
        data:
          push:
            badge: 0
            category: "lock_door_stale"
    - service: input_boolean.turn_off
      entity_id: input_boolean.stale_alarm_notifications

# Actional notification: Arm alarm and lock door
- alias: Arm alarm and lock door from notification
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: ARM_ALARM_AND_LOCK_DOOR
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.stale_alarm_notifications
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: lock.lock
      entity_id: lock.danalock_locked
    - service: notify.ios_lolphone_x
      data:
        message: "Alarm aktivert og dør låst"
        data:
          push:
            badge: 0

# Actional notification: arm alarm
- alias: Disarm alarm from notification
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: ARM_ALARM
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.stale_alarm_notifications
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.ios_lolphone_x
      data:
        message: "Alarm aktivert"
        data:
          push:
            badge: 0

# Actional notification: Lock door
- alias: Lock from notification
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: LOCK_DOOR
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.stale_alarm_notifications
    - service: lock.lock
      entity_id: lock.danalock_locked
    - service: notify.ios_lolphone_x
      data:
        message: "Dør låst"
        data:
          push:
            badge: 0
