- alias: 'Enable alarm notifications'
  trigger:
    - platform: state
      entity_id: input_boolean.stale_alarm_notifications
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
    - platform: state
      entity_id: lock.danalock_locked
  condition:
    - condition: state
      entity_id: input_boolean.stale_alarm_notifications
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.stale_alarm_notifications
