- alias: Theme home
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: disarmed
  action:
    - service: frontend.set_theme
      data:
        name: default
    - service: group.set_visibility
      entity_id: group.ute_min
      data:
        visible: True


- alias: Theme alarm pending
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: pending
  action:
    - service: frontend.set_theme
      data:
        name: alarm_pending
    - service: group.set_visibility
      entity_id: group.ute_min
      data:
        visible: False


- alias: Theme alarm active
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: armed_away
  action:
    - service: frontend.set_theme
      data:
        name: alarm_armed
