- alias: Disarm alarm (Ståle)
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'on'
  condition:
    - condition: state
      entity_id: lock.danalock_locked
      state: 'unlocked'
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'armed_away'
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'pending'
  action:
    - service: notify.ios_lolphone_x
      data:
        message: "Kommer hjem: alarm aktivert"
        data:
          push:
            badge: 0
            category: "disarm_alarm_stale"

- alias: Ask if alarm should be disarmed (Ståle)
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'on'
  condition:
    - condition: state
      entity_id: lock.danalock_locked
      state: 'locked'
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'armed_away'
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'pending'
  action:
    - service: notify.ios_lolphone_x
      data:
        message: "Kommer hjem: dør låst og alarm aktivert"
        data:
          push:
            badge: 0
            category: "disarm_alarm_and_unlock_door_stale"

- alias: Ask if door should be unlocked (Ståle)
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'on'
  condition:
    - condition: state
      entity_id: lock.danalock_locked
      state: 'locked'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'disarmed'
  action:
    - service: notify.ios_lolphone_x
      data:
        message: "Kommer hjem: dør låst"
        data:
          push:
            badge: 0
            category: "unlock_door_stale"

# Actional notification: Arm alarm and lock door
- alias: Arm alarm and lock door from notification
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISARM_ALARM_AND_UNLOCK_DOOR
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: lock.unlock
      entity_id: lock.danalock_locked

# Actional notification: arm alarm
- alias: Disarm alarm from notification
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISARM_ALARM
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm

# Actional notification: Lock door
- alias: Unlock door from notification
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: UNLOCK_DOOR
  action:
    - service: lock.unlock
      entity_id: lock.danalock_locked
