- alias: Alarm away gang notify
  trigger:
    - platform: state
      entity_id: sensor.motion_gang
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse i gangen!'
    - service: shell_command.heracam_store_image

- alias: Alarm away gang store image
  trigger:
    - platform: time
      minutes: '00'
      seconds: '/10'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
    - condition: state
      entity_id: sensor.motion_gang
      state: 'Bevegelse!'
      for:
        seconds: 10
  action:
    - service: shell_command.heracam_store_image

# Kitchen
- alias: Alarm away kjøkken
  trigger:
    - platform: state
      entity_id: sensor.motion_kitchen
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kjøkkenet!'

# Office
- alias: Alarm away kontor
  trigger:
    - platform: state
      entity_id: sensor.motion_kontor
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kontoret!'
