- alias: Alarm away gang notify
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_gang_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse i gangen!'
        critical: 1
    - service: shell_command.heracam_nc250_store_image
    - service: shell_command.heracam_nc260_store_image

- alias: Alarm away gang store image
  trigger:
    - platform: time
      seconds: '/20'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    - condition: state
      entity_id: sensor.motion_gang
      state: 'Bevegelse!'
      for:
        seconds: 20
  action:
    - service: shell_command.heracam_nc250_store_image
    - service: shell_command.heracam_nc260_store_image

# Kitchen
- alias: Alarm away kjøkken
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_kitchen_top_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.multi_kitchen_top_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kjøkkenet!'
        critical: 1

# Office
- alias: Alarm away kontor
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_kontor_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kontoret!'
        critical: 1
