- alias: Alarm away door back
  trigger:
    - platform: state
      entity_id: binary_sensor.door_back_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Door alarm!'
        message: 'Døra på baksiden er åpnet!'


- alias: Alarm away door front
  trigger:
    - platform: state
      entity_id: binary_sensor.door_front_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Door alarm!'
        message: 'Døra på framsiden er åpnet!'
