- alias: Alarm away gang notify
  trigger:
    - platform: state
      entity_id: sensor.motion_gang
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse i gangen!'
    - service: shell_command.heracam_nc250_store_image
    - service: shell_command.heracam_nc260_store_image

- alias: Alarm away gang store image
  trigger:
    - platform: time
      seconds: '/20'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    - condition: state
      entity_id: sensor.motion_gang
      state: 'Bevegelse!'
      for:
        seconds: 20
  action:
    - service: shell_command.heracam_nc250_store_image
    - service: shell_command.heracam_nc260_store_image

# Kitchen
- alias: Alarm away kjøkken
  trigger:
    - platform: state
      entity_id: sensor.motion_sensors_kitchen
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kjøkkenet!'

# Office
- alias: Alarm away kontor
  trigger:
    - platform: state
      entity_id: sensor.motion_kontor
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.notify_all_important
      data:
        title: 'Motion alarm!'
        message: 'Bevegelse på kontoret!'
