- alias: Battery warning
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.battery_danalock
        - sensor.battery_door_front
        - sensor.battery_door_back
        - sensor.battery_smoke_living_room
        - sensor.battery_smoke_bedroom
        - sensor.battery_smoke_entrance
        - sensor.battery_smoke_office
        - sensor.battery_multi_kitchen
        - sensor.battery_multi_entrance
        - sensor.battery_refrigerator
        - sensor.battery_freezer_kitchen
        - sensor.battery_freezer_bod
        - sensor.plant_1_battery
        - sensor.plant_2_battery
      below: 20
    - platform: time
      at: '09:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    - condition: template
      value_template: '{{ trigger.from_state | float > 20 }}'
    - condition: template
      value_template: '{{ not is_state("trigger.from_state", "N/A") and trigger.to_state <= 20 }}'
  action:
    - service: notify.ios_lolphone_x
      data_template:
        title: 'Battery warning'
        message: >
          '{{ trigger.from_state.attributes.friendly_name }} has
          {{ trigger.from_state.state }}% battery.'
        data:
          push:
            badge: 0
