- alias: Battery danalock
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_danalock
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_danalock
      device: states.sensor.battery_danalock

- alias: Battery door front
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_door_front
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_door_front
      device: states.sensor.battery_door_front

- alias: Battery door back
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_door_back
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_door_back
      device: states.sensor.battery_door_back

- alias: Battery door back
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_smoke_living_room
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_smoke_living_room
      device: states.sensor.battery_smoke_living_room

- alias: Battery smoke bedroom
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_smoke_bedroom
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_smoke_bedroom
      device: states.sensor.battery_smoke_bedroom

- alias: Battery smoke sensor entrance
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_smoke_entrance
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_smoke_entrance
      device: states.sensor.battery_smoke_entrance

- alias: Battery smoke sensor office
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_smoke_office
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_smoke_office
      device: states.sensor.battery_smoke_office

- alias: Battery multi kitchen
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_multi_kitchen
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_multi_kitchen
      device: states.sensor.battery_multi_kitchen

- alias: Battery multi entrance
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_multi_entrance
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: group.battery_multi_entrance
      device: states.sensor.battery_multi_entrance

- alias: Battery refrigerator
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_refrigerator
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: sensor.battery_refrigerator
      device: states.sensor.battery_refrigerator

- alias: Battery freezer kitchen
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_freezer_kitchen
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: sensor.battery_freezer_kitchen
      device: states.sensor.battery_freezer_kitchen

- alias: Battery freezer bod
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.battery_freezer_bod
  action:
    service: script.group_visibility_battery
    data:
      group_to_hide: sensor.battery_freezer_bod
      device: states.sensor.battery_freezer_bod
