# HASS startup

- alias: HeraCam startup on
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: switch.turn_off
      entity_id: switch.doorbell_relay


- alias: HeraCam startup off
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
  action:
    - service: switch.turn_on
      entity_id: switch.doorbell_relay


# Alarm state changed

- alias: HeraCam On
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: pending
  action:
    - service: switch.turn_off
      entity_id: switch.doorbell_relay


- alias: HeraCam group on
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: armed_away
  action:
    - service: switch.turn_off
      entity_id: switch.doorbell_relay


- alias: HeraCam Off
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: disarmed
  action:
    - service: switch.turn_on
      entity_id: switch.doorbell_relay
