- alias: Refrigerator alarm 5 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      for:
        minutes: 5
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 5 minutter'

- alias: Refrigerator alarm 15 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      for:
        minutes: 15
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 15 minutter'

- alias: Refrigerator alarm 60 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      for:
        minutes: 60
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 60 minutter'
