- alias: Freezer kitchen alarm 5 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      to: 'on'
      for:
        minutes: 5
  action:
    - service: notify.notify_all_important
      data:
        title: 'Freezer alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 5 minutter'

- alias: Freezer kitchen alarm 10 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.notify_all_important
      data:
        title: 'Freezer alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 10 minutter'

- alias: Freezer kitchen alarm 15 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      to: 'on'
      for:
        minutes: 15
  action:
    - service: notify.notify_all_important
      data:
        title: 'Freezer alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 15 minutter'

- alias: Freezer kitchen alarm 20 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      to: 'on'
      for:
        minutes: 20
  action:
    - service: notify.notify_all_important
      data:
        title: 'Freezer alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 20 minutter'

- alias: Freezer kitchen alarm 30 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      to: 'on'
      for:
        minutes: 30
  action:
    - service: notify.notify_all_important
      data:
        title: 'Freezer alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 30 minutter'

- alias: Freezer kitchen alarm 60 min
  trigger:
    - platform: state
      entity_id: binary_sensor.freezer_kitchen_sensor_38_0
      to: 'on'
      for:
        minutes: 60
  action:
    - service: notify.notify_all_important
      data:
        title: 'Freezer alarm!'
        message: 'Fryseren på kjøkkenet har stått oppe i 60 minutter'
