- alias: Stue natt ukedag
  trigger:
    - platform: time
      minutes: '/5'
      seconds: '5'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '22:00:00'
      before: '5:00:00'
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_natt_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ temp + el_comp }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_natt_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ (temp + el_comp - 0.5) | int }}

- alias: Stue natt helg
  trigger:
    - platform: time
      minutes: '/5'
      seconds: '10'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '23:30:00'
      before: '08:30:00'
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_natt_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ temp + el_comp }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_natt_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ (temp + el_comp - 0.5) | int }}

- alias: Stue morgen ukedag
  trigger:
    - platform: time
      minutes: '/5'
      seconds: '15'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '05:00:00'
      before: '14:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_morgen_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ temp + el_comp }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_morgen_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ (temp + el_comp - 0.5) | int }}

- alias: Stue ettermiddag ukedag
  trigger:
    - platform: time
      minutes: '/5'
      seconds: '20'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '14:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ temp + el_comp }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ (temp + el_comp - 0.5) | int }}

- alias: Stue morgen helg
  trigger:
    - platform: time
      minutes: '/5'
      seconds: '25'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '08:30:00'
      before: '22:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ temp + el_comp }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {{ (temp + el_comp - 0.5) | int }}


# Door state changed

- alias: Living room door opened
  trigger:
    - platform: state
      entity_id: group.door_sensors_living_room_kitchen
      to: 'on'
      for:
        seconds: 30
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.stue_termostat
        operation_mode: 'off'

- alias: Living room door closed
  trigger:
    - platform: state
      entity_id: group.door_sensors_living_room_kitchen
      to: 'off'
      for:
        minutes: 2
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.stue_termostat
        operation_mode: 'heat'
