# Soverom helg

- alias: Soverom morgen helg
  trigger:
    - platform: time
      at: "09:30:00"
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '09:30:00'
      before: '12:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.soverom_wakeup_heat
      state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_slider.soverom_wakeup_temperatur.state | float }}"


- alias: Soverom dag helg
  trigger:
    - platform: time
      at: "12:00:00"
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '12:00:00'
      before: '20:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_slider.soverom_dagtid_temperatur.state | float }}"
