# Kontor

- alias: Kontor natt
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_number.kontor_temperatur.state | float }}"

- alias: Kontor morgen ukedag
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'disarmed'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.tina_jobb_i_dag_sjekk
          state: 'on'
        - condition: state
          entity_id: binary_sensor.tina_jobb_i_dag_sjekk
          state: 'True'
        - condition: state
          entity_id: input_boolean.office_force_morning_heat
          state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_number.kontor_morning_temperatur.state | float }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.office_force_morning_heat

- alias: Kontor ettermiddag ukedag
  trigger:
    - platform: time
      at: "12:00:00"
    - platform: time
      at: "13:00:00"
    - platform: time
      at: "14:00:00"
    - platform: time
      at: "15:00:00"
    - platform: time
      at: "16:00:00"
    - platform: time
      at: "17:00:00"
    - platform: time
      at: "18:00:00"
    - platform: time
      at: "19:00:00"
    - platform: time
      at: "20:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
    - condition: or
      conditions:

      # Hjemmekontor - ingen bevegelse på 4 timer
      - condition: and
        conditions:
        - condition: state
          entity_id: 'binary_sensor.hjemmekontor'
          state: 'off'
        - condition: template
          value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.multi_kontor_sensor.last_changed)) > (60*60*4)}}'

      # Ingen bevegelse på 3 timer
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.multi_kontor_sensor.last_changed)) > (60*60*4)}}'

      # Alt annet - TODO: NEED MORE WORK
      - condition: and
        conditions:
        - condition: state
          entity_id: 'binary_sensor.hjemmekontor'
          state: 'off'
        - condition: state
          entity_id: 'binary_sensor.hjemmekontor'
          state: 'off'

  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_number.kontor_temperatur.state | float }}"
