- alias: Gang heat off
  trigger:
    - platform: state
      entity_id: sensor.motion_kitchen
      to: 'Bevegelse!'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.gang_termostat
        operation_mode: 'off'

- alias: Gang heat on
  trigger:
    - platform: state
      entity_id: sensor.motion_kitchen
  condition:
    - condition: state
      entity_id: sensor.motion_kitchen
      state: 'Ingen bevegelse'
      for:
        minutes: 10
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.gang_termostat
        operation_mode: 'auto'
