# Soverom ukedag

- alias: Soverom morgen ukedag
  trigger:
    - platform: time
      after: "07:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.soverom_wakeup_heat
      state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_slider.soverom_wakeup_temperatur.state | float }}"


- alias: Soverom dag ukedag
  trigger:
    - platform: time
      after: "10:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_slider.soverom_dagtid_temperatur.state | float }}"


- alias: Soverom kveld hver dag
  trigger:
    - platform: time
      after: "20:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_slider.soverom_natt_temperatur.state | float }}"
