# Soverom ukedag

- alias: Soverom morgen ukedag
  trigger:
    - platform: time
      at: '07:30:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '07:30:00'
      before: '10:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.soverom_wakeup_heat
      state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_number.soverom_wakeup_temperatur.state | float }}"


- alias: Soverom dag ukedag
  trigger:
    - platform: time
      at: "10:00:00"
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '10:00:00'
      before: '20:30:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_number.soverom_dagtid_temperatur.state | float }}"


- alias: Soverom kveld hver dag
  trigger:
    - platform: time
      at: '20:30:00'
    - platform: homeassistant
      event: start
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    - condition: time
      after: '20:30:00'
      before: '07:30:00'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: >-
          {% if states.input_number.soverom_natt_temperatur.state == unknown %}
            19
          {% elif states.sensor.temp_ute_temperature.state == unknown %}
            {{ states.input_number.soverom_natt_temperatur.state | float }}
          {% else %}
            {% set new_temp = states.input_number.soverom_natt_temperatur.state | float %}
            {% set outdoor_temp = states.sensor.temp_ute_temperature.state | float | round(0) %}
            {% if outdoor_temp >= 10 %}
              {{ new_temp }}
            {% elif outdoor_temp > -20 %}
              {{ (new_temp + ((outdoor_temp / 20) - 0.5) * -1) | round(1) }}
            {% else %}
              {{ (new_temp + 1.5) | round(1) }}
            {% endif %}
          {% endif %}
