# Kontor

- alias: Kontor natt
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_number.kontor_temperatur.state | float }}"

- alias: Kontor morgen ukedag
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'disarmed'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.tina_jobb_i_dag_sjekk
          state: 'on'
        - condition: state
          entity_id: binary_sensor.tina_jobb_i_dag_sjekk
          state: 'True'
        - condition: state
          entity_id: input_boolean.office_force_morning_heat
          state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_number.kontor_morning_temperatur.state | float }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.office_force_morning_heat

- alias: Kontor ettermiddag ukedag
  trigger:
    - platform: time
      at: "11:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: 'binary_sensor.hjemmekontor'
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_number.kontor_temperatur.state | float }}"
