- alias: Stue natt
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 10
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.living_room_fireplace
  condition:
    - condition: or
      conditions:
        # Natt ukedag
        - condition: and
          conditions:
            - condition: time
              after: '22:00:00'
              before: '4:00:00'
            - condition: state
              entity_id: binary_sensor.workday_today
              state: 'on'
            - condition: state
              entity_id: binary_sensor.workday_tomorrow
              state: 'on'
        # Fredag
        - condition: and
          conditions:
            - condition: time
              after: '23:30:00'
              before: '4:00:00'
            - condition: state
              entity_id: binary_sensor.workday_today
              state: 'on'
            - condition: state
              entity_id: binary_sensor.workday_tomorrow
              state: 'off'
        # Lørdag
        - condition: and
          conditions:
            - condition: time
              after: '23:30:00'
              before: '08:30:00'
            - condition: state
              entity_id: binary_sensor.workday_today
              state: 'off'
            - condition: state
              entity_id: binary_sensor.workday_tomorrow
              state: 'off'
        # Søndag
        - condition: and
          conditions:
            - condition: time
              after: '22:30:00'
              before: '08:30:00'
            - condition: state
              entity_id: binary_sensor.workday_today
              state: 'off'
            - condition: state
              entity_id: binary_sensor.workday_tomorrow
              state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_natt_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_living_room.state | float %}
          {{ (temp + el_comp - fireplace) }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_natt_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_kitchen.state | float %}
          {{ (temp + el_comp - 0.5 - fireplace) | int }}

- alias: Stue morgen ukedag
  trigger:
    - platform: time_patterns
      minutes: '/5'
      seconds: 20
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.living_room_fireplace
    - platform: state
      entity_id: input_number.stue_morgen_temperatur
  condition:
    - condition: time
      after: '04:00:00'
      before: '14:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_morgen_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_living_room.state | float %}
          {{ (temp + el_comp - fireplace) }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_morgen_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_kitchen.state | float %}
          {{ (temp + el_comp - 0.5 - fireplace) | int }}

- alias: Stue ettermiddag ukedag
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 30
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.living_room_fireplace
    - platform: state
      entity_id: input_number.stue_dagtid_temperatur
  condition:
    - condition: time
      after: '14:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_living_room.state | float %}
          {{ (temp + el_comp - 0.5 - fireplace) }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_kitchen.state | float %}
          {{ (temp + el_comp - 0.5 - fireplace) | int }}

- alias: Stue morgen helg
  trigger:
    - platform: v
      minutes: '/5'
      seconds: 40
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.living_room_fireplace
    - platform: state
      entity_id: input_number.stue_dagtid_temperatur
  condition:
    - condition: time
      after: '08:30:00'
      before: '22:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_living_room.state | float %}
          {{ (temp + el_comp - 0.5 - fireplace) }}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kja_kken
        temperature: >-
          {% set temp = states.input_number.stue_dagtid_temperatur.state | float %}
          {% set el_comp = states.sensor.electricity_temperature.state | float %}
          {% set fireplace = states.sensor.living_room_fireplace_kitchen.state | float %}
          {{ (temp + el_comp - 0.5 - fireplace) | int }}


# Door state changed

- alias: Living room door opened
  trigger:
    - platform: state
      entity_id: group.door_sensors_living_room_kitchen
      to: 'on'
      for:
        seconds: 30
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.stue_termostat
        operation_mode: 'off'

- alias: Living room door closed
  trigger:
    - platform: state
      entity_id: group.door_sensors_living_room_kitchen
      to: 'off'
      for:
        minutes: 2
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.stue_termostat
        operation_mode: 'heat'
    # TODO: Add Mill heating


- alias: Living room fireplace reset
  trigger:
    - platform: time_pattern
      minutes: 1
      seconds: 00
    - platform: state
      entity_id: input_boolean.living_room_fireplace
      to: 'on'
      for:
        hours: 4
  condition:
    - condition: state
      entity_id: input_boolean.living_room_fireplace
      state: 'on'
      for:
        hours: 3
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_fireplace
