# Stue

- alias: Stue natt ukedag
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.workday_tomorrow_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: "{{ states.input_slider.stue_natt_temperatur.state | float }}"

- alias: Stue natt helg
  trigger:
    - platform: time
      at: "23:30:00"
  condition:
    - condition: state
      entity_id: binary_sensor.workday_tomorrow_sensor
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: "{{ states.input_slider.stue_natt_temperatur.state | float }}"

- alias: Stue morgen ukedag
  trigger:
    - platform: time
      at: "07:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: "{{ states.input_slider.stue_morgen_temperatur.state | float }}"

- alias: Stue ettermiddag ukedag
  trigger:
    - platform: time
      at: "16:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: "{{ states.input_slider.stue_dagtid_temperatur.state | float }}"

- alias: Stue morgen helg
  trigger:
    platform: time
    at: "08:30:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.stue_thermostat_temperatur
        value: "{{ states.input_slider.stue_dagtid_temperatur.state | float }}"


# Door state changed

- alias: Living room door opened
  trigger:
    - platform: state
      entity_id: binary_sensor.door_front_sensor_52_0
  condition:
    - condition: state
      entity_id: binary_sensor.door_front_sensor_52_0
      state: 'on'
      for:
        seconds: 30
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.stue_termostat
        temperature: 10.0

- alias: Living room door closed
  trigger:
    - platform: state
      entity_id: binary_sensor.door_front_sensor_52_0
  condition:
    - condition: state
      entity_id: binary_sensor.door_front_sensor_52_0
      state: 'off'
      for:
        minutes: 2
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: "{{ states.input_slider.stue_thermostat_temperatur.state | float }}"
