# Kontor

- alias: Kontor natt
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_slider.kontor_temperatur.state | float }}"

- alias: Kontor morgen ukedag
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.tina_home'
      state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_slider.kontor_morning_temperatur.state | float }}"

- alias: Kontor ettermiddag ukedag
  trigger:
    - platform: time
      at: "11:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: "{{ states.input_slider.kontor_temperatur.state | float }}"
