# Soverom helg

- alias: Soverom morgen helg
  trigger:
    - platform: time
      at: '09:30:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            # Lørdag
            - condition: time
              after: '07:30:00'
              before: '12:00:00'
            - condition: state
              entity_id: 'binary_sensor.workday_yesterday'
              state: 'on'
        - condition: and
          conditions:
            # Søndag
            - condition: time
              after: '09:30:00'
              before: '12:00:00'
            - condition: state
              entity_id: 'binary_sensor.workday_tomorrow'
              state: 'on'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.soverom_wakeup_heat
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_number.soverom_wakeup_temperatur.state | float }}"


- alias: Soverom dag helg
  trigger:
    - platform: time
      at: '12:00:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '12:00:00'
      before: '20:30:00'
    - condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: "{{ states.input_number.soverom_dagtid_temperatur.state | float }}"
