- alias: Gang heat off
  trigger:
    - platform: state
      entity_id: sensor.motion_sensors_kitchen
      to: 'Bevegelse!'
  condition:
    - condition: state
      entity_id: input_boolean.brewing
      state: 'off'
    - condition: time
      after: '12:00:00'
      before: '21:00:00'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.gang_termostat
        operation_mode: 'off'

- alias: Gang heat on
  trigger:
    - platform: state
      entity_id: sensor.motion_sensors_kitchen
      to: 'Ingen bevegelse'
      for:
        minutes: 15
    - platform: state
      entity_id: sensor.motion_sensors_kitchen
      to: 'Ingen bevegelse'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.brewing
      state: 'off'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.gang_termostat
        operation_mode: 'heat'
