- alias: Soverom heat off
  trigger:
    - platform: state
      entity_id: sensor.motion_kitchen
      to: 'Bevegelse!'
  condition:
    - condition: time
      after: '11:00:00'
      before: '22:00:00'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.soverom_termostat
        operation_mode: 'off'

- alias: Soverom heat on
  trigger:
    - platform: state
      entity_id: sensor.motion_kitchen
      to: 'Ingen bevegelse'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '11:00:00'
      before: '20:00:00'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.soverom_termostat
        operation_mode: 'auto'
