- alias: HeraCam startup on
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Active'
  action:
    - service: group.set_visibility
      entity_id: group.heracam
      data:
        visible: True


- alias: HeraCam startup off
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sensor.alarm_active
      state: 'Inactive'
  action:
    - service: group.set_visibility
      entity_id: group.heracam
      data:
        visible: False


- alias: HeraCam On
  trigger:
    - platform: state
      entity_id: sensor.alarm_active
      to: 'Active'
  action:
    - service: switch.turn_on
      entity_id: switch.heracam_relay


- alias: HeraCam group on
  trigger:
    - platform: state
      entity_id: switch.heracam_relay
      to: 'on'
      for:
        minutes: 1
  action:
    - service: group.set_visibility
      entity_id: group.heracam
      data:
        visible: True


- alias: HeraCam Off
  trigger:
    - platform: state
      entity_id: sensor.alarm_active
      to: 'Inactive'
  action:
    - service: switch.turn_off
      entity_id: switch.heracam_relay
    - service: group.set_visibility
      entity_id: group.heracam
      data:
        visible: False
