- alias: Deaktiver hjemmekontor midnatt
  trigger:
    - platform: time
      at: "00:00:00"
    - platform: time
      at: "02:00:00"
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.hjemmekontor
