- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: homeassistant
      event: start
  action:
    - delay: '00:05:00'
    - service: homekit.start
