- alias: Hue down alert
  trigger:
    - platform: state
      entity_id: device_tracker.philipshuelan
      to: 'not_home'
      for:
        minutes: 5
    - platform: state
      entity_id: device_tracker.philipshuelan
      to: 'not_home'
      for:
        minutes: 15
  action:
    - service: notify.ios_lolphone_x
      data:
        title: 'Philips Hue alert!'
        message: 'Enheten svarer ikke'
