- alias: Light kitchen bench dim
  trigger:
    - platform: state
      entity_id: switch.kitchen_bardisk_switch
      to: 'off'
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.kitchen_bench_lights
        value: 1

- alias: Light kitchen bench on
  trigger:
    - platform: state
      entity_id: switch.kitchen_bardisk_switch
      to: 'on'
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.kitchen_bench_lights
        value: 2


# Detect changes

- alias: Change kitchen bench lights to off
  trigger:
    - platform: template
      value_template: "{{ states.input_number.kitchen_bench_lights.state == '0.0' }}"
  action:
    - service: shell_command.kitchen_bench_lights_off


- alias: Change kitchen bench lights to off
  trigger:
    - platform: template
      value_template: "{{ states.input_number.kitchen_bench_lights.state == '1.0' }}"
  action:
    - service: shell_command.kitchen_bench_lights_dim


- alias: Change kitchen bench lights to on
  trigger:
    - platform: template
      value_template: "{{ states.input_number.kitchen_bench_lights.state == '2.0' }}"
  action:
    - service: shell_command.kitchen_bench_lights_on
