- alias: Light kitchen off
  trigger:
    - platform: state
      entity_id: group.motion_sensors_kitchen
      to: 'off'
      for:
        minutes: 10
  action:
    - service: light.turn_on
      data:
        entity_id: light.kjkkenet
        brightness: 0
        transition: 3000

- alias: Light kitchen zero brightness
  trigger:
    - platform: numeric_state
      entity_id: group.motion_sensors_kitchen
      value_template: '{{ states.attributes.brightness }}'
      below: 1
      for:
        seconds: 10
  action:
    - service: light.turn_off
      data:
        entity_id: light.kjkkenet

- alias: Light kitchen dim on
  trigger:
    - platform: state
      entity_id: group.motion_sensors_kitchen
      to: 'on'
  condition:
    - condition: time
      after: '08:00:00'
      before: '23:59:00'
    - condition: state
      entity_id: switch.kitchen_bardisk_switch # bardisk
      state: 'on'
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: light.kjkkenet
          below: 253
          value_template: '{{ states.attributes.brightness }}'
        - condition: state
          entity_id: light.kjkkenet # taklys
          state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kjkkenet
        brightness: 254
        transition: 10
