- alias: Light kitchen bench set status
  trigger:
    - platform: state
      entity_id: switch.kitchen_bardisk_switch
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.kitchen_bench_lights
        value: >-
            {% if is_state('switch.kitchen_bardisk_switch', 'on') %}
              2
            {% elif is_state('input_boolean.guest_living_room', 'off') %}
              1
            {% else %}
              0
            {% endif %}

# Detect changes

- alias: Change kitchen bench lights to off
  trigger:
    - platform: state
      entity_id: input_number.kitchen_bench_lights
    - platform: time_pattern
      minutes: '/2'
      seconds: 00
  action:
    - service_template: >
        {% if is_state('input_number.kitchen_bench_lights', '2.0') %}
          shell_command.kitchen_bench_lights_on
        {% elif is_state('input_number.kitchen_bench_lights', '1.0') %}
          shell_command.kitchen_bench_lights_dim
        {% else %}
          shell_command.kitchen_bench_lights_on
        {% endif %}
