- alias: Light kitchen off
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_kitchen_top_sensor
      to: 'off'
      for:
        minutes: 10 # todo: 5 min if after midnight
    - platform: state
      entity_id: binary_sensor.multi_kitchen_bottom_sensor
      to: 'off'
      for:
        minutes: 10 # todo: 5 min if after midnight
  condition:
    - condition: state
      entity_id: binary_sensor.multi_kitchen_top_sensor
      state: 'off'
    - condition: state
      entity_id: binary_sensor.multi_kitchen_bottom_sensor
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.kjokkenet
        transition: 600

- alias: Light kitchen dim on (daytime)
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_kitchen_top_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.multi_kitchen_bottom_sensor
      to: 'on'
    - platform: state
      entity_id: switch.kitchen_bardisk_switch
      to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '22:59:59'
    - condition: state
      entity_id: switch.kitchen_bardisk_switch
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.multi_kitchen_top_sensor
          state: 'on'
        - condition: state
          entity_id: binary_sensor.multi_kitchen_bottom_sensor
          state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kjokkenet
        brightness: 254
        transition: 1

- alias: Light kitchen dim on (night)
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_kitchen_top_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.multi_kitchen_bottom_sensor
      to: 'on'
    - platform: state
      entity_id: switch.kitchen_bardisk_switch
      to: 'on'
  condition:
    - condition: time
      after: '23:00:00'
      before: '06:59:59'
    - condition: state
      entity_id: switch.kitchen_bardisk_switch
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.multi_kitchen_top_sensor
          state: 'on'
        - condition: state
          entity_id: binary_sensor.multi_kitchen_bottom_sensor
          state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kjokkenet
        brightness: 85
        transition: 1

# FIXME: This is triggered when 'switch.kitchen_bardisk_switch_2' is initialized
- alias: Light kitchen force on
  trigger:
    - platform: state
      entity_id: switch.kitchen_bardisk_switch_2
  condition:
    - condition: state
      entity_id: light.kjokkenet
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kjokkenet
        brightness: 254
        transition: 1

- alias: Light kitchen force off
  trigger:
    - platform: state
      entity_id: switch.kitchen_bardisk_switch_2
    - platform: state
      entity_id: switch.kitchen_bardisk_switch
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kjokkenet
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.kjokkenet
        transition: 0
