- alias: Hide spotify
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'off'
  action:
    - service: group.set_visibility
      entity_id: group.spotify
      data:
        visible: False

- alias: Show spotify
  trigger:
    - platform: state
      entity_id: input_boolean.stale_home
      to: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.spotify
      data:
        visible: True
