- alias: Nordlysvarsel notification 1
  trigger:
    - platform: state
      entity_id: sensor.nordlysvarsel_1_time
  condition:
    - condition: and
      conditions:
        # sun.elevation < -15
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: -15

        # month < may and month > august
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ now().month < 5 }}'
            - condition: template
              value_template: '{{ now().month > 8 }}'

        # Only when not on vacation
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: 'off'

        # workday = from 7, else 9
        - condition: or
          conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: binary_sensor.workday_today
                state: true
              - condition: time
                after: '07:00:00'
            - condition: and
              conditions:
              - condition: state
                entity_id: binary_sensor.workday_today
                state: false
              - condition: time
                after: '09:00:00'

        # workday tomorrow = before 23, else 02
        - condition: or
          conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: binary_sensor.workday_tomorrow
                state: true
              - condition: time
                before: '23:00:00'
            - condition: and
              conditions:
              - condition: state
                entity_id: binary_sensor.workday_tomorrow
                state: false
            - condition: and
              conditions:
              - condition: state
                entity_id: binary_sensor.workday_today
                state: false
              - condition: time
                before: '02:00:00'

        - condition: numeric_state
          entity_id: sensor.nordlysvarsel_1_time
          above: 3.5

        # Need clear sky
        - condition: or
          conditions:
            - condition: numeric_state
              entity_id: 'sensor.yr_symbol'
              above: 0
              below: 4
            - condition: numeric_state
              entity_id: 'sensor.yr_symbol'
              above: 100
              below: 104
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Nordlysvarsel'
        message: "Det er spådd {{ states('sensor.nordlysvarsel_1_time') }} KP den neste timen."
