- alias: Nordlysvarsel notification 1
  trigger:
    - platform: state
      entity_id: sensor.nordlysvarsel_1_time
  condition:
    - condition: or
      conditions:
        condition: and
        conditions:
          - condition: numeric_state
            entity_id: sun.sun
            value_template: '{{ state.attributes.elevation }}'
            below: -15
          - condition: numeric_state
            entity_id: sensor.nordlysvarsel_1_time
            above: 3.3
        condition: and
        conditions:
          - condition: numeric_state
            entity_id: sun.sun
            value_template: '{{ state.attributes.elevation }}'
            below: -10
          - condition: numeric_state
            entity_id: sensor.nordlysvarsel_1_time
            above: 4.0

    # Only when not on vacation
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'

    - condition: time
      before: '02:00:00'
    - condition: time
      after: '10:00:00'

    # Need clear sky
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: 'sensor.yr_symbol'
          above: 0
          below: 4
        - condition: numeric_state
          entity_id: 'sensor.yr_symbol'
          above: 100
          below: 104
  action:
    - service: notify.ios_lolphone_x
      data:
        title: 'Nordlysvarsel'
        message: "Det er spådd {{ states('sensor.nordlysvarsel_1_time') }} KP den neste timen."


- alias: Nordlysvarsel notification 4
  trigger:
    - platform: state
      entity_id: sensor.nordlysvarsel_4_timer
  condition:
    - condition: or
      conditions:
        condition: and
        conditions:
          - condition: numeric_state
            entity_id: sun.sun
            value_template: '{{ state.attributes.elevation }}'
            below: -15
          - condition: numeric_state
            entity_id: sensor.nordlysvarsel_1_time
            above: 3.3
        condition: and
        conditions:
          - condition: numeric_state
            entity_id: sun.sun
            value_template: '{{ state.attributes.elevation }}'
            below: -10
          - condition: numeric_state
            entity_id: sensor.nordlysvarsel_1_time
            above: 4.0

    # Only when not on vacation
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'

    - condition: time
      before: '02:00:00'
    - condition: time
      after: '10:00:00'

    # Need clear sky
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: 'sensor.yr_symbol'
          above: 0
          below: 4
        - condition: numeric_state
          entity_id: 'sensor.yr_symbol'
          above: 100
          below: 104
  action:
    - service: notify.ios_lolphone_x
      data:
        title: 'Nordlysvarsel'
        message: "Det er spådd {{ states('sensor.nordlysvarsel_4_timer') }} KP om timer."
