- alias: Adjust receiver fans rear
  trigger:
    - platform: state
      entity_id: input_number.receiver_fan_speed_rear
  action:
    - service: mqtt.publish
      data:
        topic: 'hass/living_room/receiver/fan'
        qos: 1
        retain: true
        payload_template: FA,{{ states('input_number.receiver_fan_speed_rear') }}

- alias: Adjust receiver fans internal
  trigger:
    - platform: state
      entity_id: input_number.receiver_fan_speed_internal
  action:
    - service: mqtt.publish
      data:
        topic: 'hass/living_room/receiver/fan'
        qos: 1
        retain: true
        payload_template: FA,{{ states('input_number.receiver_fan_speed_internal') }}
