- alias: Refrigerator alarm 5 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 5
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 5 minutter'

- alias: Refrigerator alarm 10 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 10 minutter'

- alias: Refrigerator alarm 15 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 15
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 15 minutter'

- alias: Refrigerator alarm 20 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 20
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 20 minutter'

- alias: Refrigerator alarm 30 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 30
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 30 minutter'

- alias: Refrigerator alarm 60 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 60
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 60 minutter'

- alias: Refrigerator alarm 90 min
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        minutes: 90
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 90 minutter'

- alias: Refrigerator alarm 2 timer
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        hours: 2
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 2 timer'

- alias: Refrigerator alarm 3 timer
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        hours: 3
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 3 timer'

- alias: Refrigerator alarm 4 timer
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        hours: 4
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 4 timer'

- alias: Refrigerator alarm 6 timer
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        hours: 6
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 6 timer'

- alias: Refrigerator alarm 12 timer
  trigger:
    - platform: state
      entity_id: binary_sensor.refrigerator_kitchen_sensor
      to: 'on'
      for:
        hours: 12
  action:
    - service: notify.notify_all_important
      data:
        title: 'Refrigerator alarm!'
        message: 'Kjøleskapsdøra har stått oppe i 12 timer'
