- alias: Vise reise morgen
  trigger:
    - platform: time
      after: '06:00:00'
    - platform: state
      entity_id: input_boolean.stale_home
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '06:00:00'
      before: '18:00:00'
    - condition: state
      entity_id: input_boolean.stale_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.stale_job
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.reise_til_jobb
      data:
        visible: True
    - service: group.set_visibility
      entity_id: group.reise_hjem
      data:
        visible: False

- alias: Vise reise hjem ettermiddag
  trigger:
    - platform: time
      after: '12:00:00'
    - platform: state
      entity_id: input_boolean.stale_job
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '12:00:00'
      before: '23:30:00'
    - condition: state
      entity_id: input_boolean.stale_home
      state: 'off'
    - condition: state
      entity_id: input_boolean.stale_job
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.reise_til_jobb
      data:
        visible: False
    - service: group.set_visibility
      entity_id: group.reise_hjem
      data:
        visible: True

- alias: Fjerne reiser
  trigger:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      to: 'off'
  action:
    - service: group.set_visibility
      entity_id: group.reise_til_jobb
      data:
        visible: False
    - service: group.set_visibility
      entity_id: group.reise_hjem
      data:
        visible: False
