# Smoke
- alias: Smoke Sensor Entrance Smoke
  trigger:
    - platform: state
      entity_id: sensor.smoke_gang_smoke_2
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_smoke_2
      state: '254'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Brann!! '
        message: 'Røyk i gangen!'


- alias: Smoke Sensor Entrance NOSMOKE
  trigger:
    - platform: state
      entity_id: sensor.smoke_gang_smoke_2
      from: '254'
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_smoke_2
      state: '0'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Alert: '
        message: 'Røyken er borte fra gangen.'



# Temperature
- alias: Smoke Sensor Entrance Temperature HIGH
  trigger:
    - platform: state
      entity_id: sensor.smoke_gang_heat_2
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.smoke_gang_heat_2
        state: '254'
      - condition: numeric_state
        entity_id: sensor.smoke_gang_temperature
        above: 35
  action:
    - service: notify.notify_all_important
      data:
        title: 'Brann!! '
        message: 'Veldig varmt i gangen!'


- alias: Smoke Sensor Entrance Temperature Normal
  trigger:
    - platform: state
      entity_id: sensor.smoke_gang_heat_2
      from: '254'
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_heat_2
      state: '0'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Alert! '
        message: 'Normal temperatur i gangen igjen.'
