# Smoke
- alias: Smoke Sensor Office Smoke
  trigger:
    - platform: state
      entity_id: sensor.smoke_kontor_smoke_48_1
  condition:
    - condition: state
      entity_id: sensor.smoke_kontor_smoke_48_1
      state: '254'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Brann!! '
        message: 'Røyk på kontoret!'


- alias: Smoke Sensor Office NOSMOKE
  trigger:
    - platform: state
      entity_id: sensor.smoke_kontor_smoke_48_1
      from: '254'
  condition:
    - condition: state
      entity_id: sensor.smoke_kontor_smoke_48_1
      state: '0'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Alert: '
        message: 'Røyken er borte på kontoret.'



# Temperature
- alias: Smoke Sensor Office Temperature HIGH
  trigger:
    - platform: state
      entity_id: sensor.smoke_kontor_heat_48_4
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.smoke_kontor_heat_48_4
        state: '254'
      - condition: numeric_state
        entity_id: sensor.smoke_kontor_temperature_48_1
        above: 35
  action:
    - service: notify.notify_all_important
      data:
        title: 'Brann!! '
        message: 'Veldig varmt på kontoret!'


- alias: Smoke Sensor Office Temperature Normal
  trigger:
    platform: state
    entity_id: sensor.smoke_kontor_heat_48_4
    from: '254'
  condition:
    - condition: state
      entity_id: sensor.smoke_kontor_heat_48_4
      state: '0'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Alert! '
        message: 'Normal temperatur på kontoret igjen.'
