# Smoke
- alias: Smoke Sensor Entrance Smoke
  trigger:
    platform: state
    entity_id: sensor.smoke_gang_smoke_47_1
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_smoke_47_1
      state: '254'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Brann!! '
        message: 'Røyk i gangen!'


- alias: Smoke Sensor Entrance NOSMOKE
  trigger:
    platform: state
    entity_id: sensor.smoke_gang_smoke_47_1
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_smoke_47_1
      state: '0'
  action:
    service: notify.ios_lolphone_7
    data:
      title: 'Alert: '
      message: 'Røyken er borte fra gangen...'



# Temperature
- alias: Smoke Sensor Entrance Temperature HIGH
  trigger:
    platform: state
    entity_id: sensor.smoke_gang_heat_47_4
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.smoke_gang_heat_47_4
        state: '254'
      - condition: numeric_state
        entity_id: sensor.smoke_gang_temperature_47_1
        above: 35
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Brann!! '
        message: 'Veldig varmt i gangen!'


- alias: Smoke Sensor Entrance Temperature Normal
  trigger:
    platform: state
    entity_id: sensor.smoke_gang_heat_47_4
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_heat_47_4
      state: '0'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Alert! '
        message: 'Normal temperatur i gangen igjen'
