# Smoke
- alias: Smoke Sensor Bedroom Smoke
  trigger:
    - platform: state
      entity_id: sensor.smoke_soverom_smoke_2
  condition:
    - condition: state
      entity_id: sensor.smoke_soverom_smoke_2
      state: '254'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Brann!! '
        message: 'Røyk på soverommet!'


- alias: Smoke Sensor Bedroom NOSMOKE
  trigger:
    - platform: state
      entity_id: sensor.smoke_soverom_smoke_2
      from: '254'
  condition:
    - condition: state
      entity_id: sensor.smoke_soverom_smoke_2
      state: '0'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Alert: '
        message: 'Røyken er borte på soverommet.'



# Temperature
- alias: Smoke Sensor Bedroom Temperature HIGH
  trigger:
    - platform: state
      entity_id: sensor.smoke_soverom_heat_2
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.smoke_soverom_heat_2
        state: '254'
      - condition: numeric_state
        entity_id: sensor.smoke_soverom_temperature
        above: 35
  action:
    - service: notify.notify_all_important
      data:
        title: 'Brann!! '
        message: 'Veldig varmt på soverommet!'


- alias: Smoke Sensor Bedroom Temperature Normal
  trigger:
    - platform: state
      entity_id: sensor.smoke_soverom_heat_2
      from: '254'
  condition:
    - condition: state
      entity_id: sensor.smoke_soverom_heat_2
      state: '0'
  action:
    - service: notify.notify_all_important
      data:
        title: 'Alert! '
        message: 'Normal temperatur på soverommet igjen.'
