# Smoke
- alias: Smoke Sensor Bedroom Smoke
  trigger:
    platform: state
    entity_id: sensor.smoke_soverom_smoke_50_1
  condition:
    - condition: state
      entity_id: sensor.smoke_soverom_smoke_50_1
      state: '254'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Brann!! '
        message: 'Røyk på soverommet!'


- alias: Smoke Sensor Bedroom NOSMOKE
  trigger:
    platform: state
    entity_id: sensor.smoke_soverom_smoke_50_1
  condition:
    - condition: state
      entity_id: sensor.smoke_soverom_smoke_50_1
      state: '0'
  action:
    service: notify.ios_lolphone_7
    data:
      title: 'Alert: '
      message: 'Røyken er borte på soverommet...'



# Temperature
- alias: Smoke Sensor Bedroom Temperature HIGH
  trigger:
    platform: state
    entity_id: sensor.smoke_soverom_heat_50_4
  condition:
    - condition: or
      - condition: state
        entity_id: sensor.smoke_soverom_heat_50_4
        state: '254'
      - condition: numeric_state
        entity_id: sensor.smoke_soverom_temperature_50_1
        above: 35
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Brann!! '
        message: 'Veldig varmt på soverommet!'


- alias: Smoke Sensor Bedroom Temperature Normal
  trigger:
    platform: state
    entity_id: sensor.smoke_soverom_heat_50_4
  condition:
    - condition: state
      entity_id: sensor.smoke_soverom_heat_50_4
      state: '0'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Alert! '
        message: 'Normal temperatur på soverommet igjen'
