# Smoke
- alias: Smoke Sensor Entrance Smoke
  trigger:
    platform: state
    entity_id: sensor.smoke_gang_smoke_47_1
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_smoke_47_1
      state: '254'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Brann!! '
        message: 'Røyk i gangen!'


- alias: Smoke Sensor Entrance NOSMOKE
  trigger:
    platform: state
    entity_id: sensor.smoke_gang_smoke_47_4
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_smoke_47_4
      state: '0'
  action:
    service: notify.ios_lolphone_7
    data:
      title: 'Smoke entrance: '
      message: 'No more smoke...'



# Temperature
- alias: Heat entrance high
  trigger:
    platform: numeric_state
    entity_id: sensor.smoke_gang_heat_47_4
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_heat_47_4
      state: '254'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Brann!! '
        message: 'Veldig varmt i gangen!'


- alias: Heat entrance normal
  trigger:
    platform: numeric_state
    entity_id: sensor.smoke_gang_heat_47_4
  condition:
    - condition: state
      entity_id: sensor.smoke_gang_heat_47_4
      state: '0'
  action:
    - service: notify.ios_lolphone_7
      data:
        title: 'Alert! '
        message: 'Normal temperatur i gangen igjen'
