# Soverom helg

- alias: Soverom morgen helg
  trigger:
    - platform: time
      after: "09:30:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.soverom_wakeup_heat
      state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: '{{ states.input_slider.slider_soverom_wakeup_temperatur.state | int }}'


- alias: Soverom dag helg
  trigger:
    - platform: time
      after: "12:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: '{{ states.input_slider.slider_soverom_dagtid_temperatur.state | int }}'
