# Soverom ukedag

- alias: Soverom morgen ukedag
  trigger:
    platform: time
    after: "07:30:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 20


- alias: Soverom dag ukedag
  trigger:
    platform: time
    after: "10:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 17


- alias: Soverom kveld hver dag
  trigger:
    platform: time
    after: "20:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 19
