# Soverom helg

- alias: Soverom morgen helg
  trigger:
    platform: time
    after: "09:30:00"
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 20


- alias: Soverom dag helg
  trigger:
    platform: time
    after: "12:00:00"
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 17


- alias: Soverom kveld helg
  trigger:
    platform: time
    after: "21:00:00"
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 19


- alias: Soverom natt helg
  trigger:
    platform: time
    after: "00:00:00"
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: 19
