- alias: Arm alarm (Ståle)
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '2:00'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.gang_termostat
        operation_mode: 'auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.soverom_termostat
        operation_mode: 'auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.stue_termostat
        operation_mode: 'auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.kontor_termostat
        operation_mode: 'auto'
