- alias: Turn TV off
  trigger:
    - platform: state
      entity_id: device_tracker.pioneer_avr
      to: 'not_home'
    - platform: state
      entity_id: media_player.pioneer_avr
      to: 'off'
    - platform: state
      entity_id: device_tracker.philips_tv
      to: 'home'
      for:
        minutes: 2
    - platform: state
      entity_id: device_tracker.philips_tv
      to: 'home'
      for:
        minutes: 5
    - platform: state
      entity_id: device_tracker.philips_tv
      to: 'home'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: device_tracker.pioneer_avr
      state: 'not_home'
    - condition: state
      entity_id: media_player.pioneer_avr
      state: 'off'
    - condition: state
      entity_id: device_tracker.philips_tv
      state: 'home'
  action:
    - service: shell_command.tv_off
