- alias: Turn TV off
  trigger:
    # Receiver
    - platform: state
      entity_id: media_player.pioneer_avr
      to: 'off'
      for:
        minutes: 3
    - platform: state
      entity_id: media_player.pioneer_avr
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: device_tracker.philips_tv
      to: 'home'
      for:
        minutes: 3
    # TV
    - platform: state
      entity_id: device_tracker.philips_tv
      to: 'not_home'
      for:
        minutes: 5
    - platform: state
      entity_id: device_tracker.philips_tv
      to: 'not_home'
      for:
        minutes: 10
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: media_player.pioneer_avr
              state: 'off'
            - condition: state
              entity_id: device_tracker.philips_tv
              state: 'home'
        - condition: and
          conditions:
            - condition: state
              entity_id: media_player.pioneer_avr
              state: 'on'
            - condition: state
              entity_id: device_tracker.philips_tv
              state: 'not_home'
  action:
    - service: shell_command.tv_off
