- alias: 'Update Available Notifications'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.ios_lolphone_x
      data:
        title: 'New version!'
        message: 'Update for Home Assistant is available.'
