- alias: Ferie modus on
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.kontor_termostat, climate.soverom_termostat, climate.stue_termostat
        temperature: '{{ input_slider.ferie_temperatur }}'

- alias: Ferie modus off
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.kontor_termostat
        temperature: '{{ input_slider.kontor_temperatur }}'
    - service: climate.set_temperature
      data:
        entity_id: climate.soverom_termostat
        temperature: '{{ input_slider.soverom_natt_temperatur }}'
    - service: climate.set_temperature
      data:
        entity_id: climate.stue_termostat
        temperature: '{{ input_slider.stue_dagtid_temperatur }}'
