- alias: Ferie modus on
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'
  action:
    - service: input_number.select_value
      data_template:
        entity_id: input_number.stue_thermostat_temperatur
        value: "{{ states.input_number.ferie_temperatur.state | float }}"
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat, climate.soverom_termostat, climate.stue_termostat
        temperature: "{{ states.input_number.ferie_temperatur.state | float }}"

- alias: Ferie modus off
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.kontor_termostat
        temperature: '{{ input_number.kontor_temperatur }}'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.soverom_termostat
        temperature: '{{ input_number.soverom_natt_temperatur }}'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.stue_termostat
        temperature: "{{ states.input_number.stue_dagtid_temperatur.state | float }}"
