# Soloppgang

- alias: Vitrineskap changed
  trigger:
    - platform: state
      entity_id: input_number.vitrineskap_dimmer
  action:
    - service: shell_command.vitrineskap_dim

# 60 min after sunrise
- alias: Vitrineskap soloppgang 1
  trigger:
    - platform: sun
      event: sunrise
      offset: "01:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 4

# 90 min after sunrise
- alias: Vitrineskap soloppgang 2
  trigger:
    - platform: sun
      event: sunrise
      offset: "02:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 5

# 120 min after sunrise
- alias: Vitrineskap soloppgang 3
  trigger:
    - platform: sun
      event: sunrise
      offset: "02:30:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 6

# 150 min after sunrise
- alias: Vitrineskap soloppgang 4
  trigger:
    - platform: sun
      event: sunrise
      offset: "03:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 7

# 180 min after sunrise
- alias: Vitrineskap soloppgang 5
  trigger:
    - platform: sun
      event: sunrise
      offset: "04:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 8



# Solnedgang

- alias: Vitrineskap solnedgang
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 3

# 60 min before sunset
- alias: Vitrineskap solnedgang 1
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 4

# 90 min before sunset
- alias: Vitrineskap solnedgang 2
  trigger:
    - platform: sun
      event: sunset
      offset: "-02:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 5

# 120 min before sunset
- alias: Vitrineskap solnedgang 3
  trigger:
    - platform: sun
      event: sunset
      offset: "-02:30:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 6

# 150 min before sunset
- alias: Vitrineskap solnedgang 4
  trigger:
    - platform: sun
      event: sunset
      offset: "-03:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 7

# 180 min before sunset
- alias: Vitrineskap solnedgang 5
  trigger:
    - platform: sun
      event: sunset
      offset: "-04:00:00"
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.vitrineskap_dimmer
        value: 8


# Lytt etter endringer

- alias: Taklys endringer
  trigger:
    - platform: state
      entity_id: light.stua
  action:
    - service: shell_command.vitrineskap_dim
